name: Create assets

on:
  workflow_call:
  workflow_dispatch: 

jobs:
  # Create assets
  assets:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      BRANCH: assets
    steps:
      
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Install genbadge
        run: pip install genbadge[tests,coverage]

      - uses: actions/download-artifact@v3
        with:
          name: test-reports
          path: reports

      - name: Generate badges
        run: |
          genbadge tests -o assets/badges/tests-badge.svg
          genbadge coverage -o assets/badges/coverage-badge.svg
          
      - name: Debug directory
        run: ls  

      - name: Commit and push badges
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets
          git commit -m "Created assets"
          git push origin ${{ env.BRANCH }}