name: Create assets

on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: [assets]

jobs:
  # Create badges
  create-badges:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    continue-on-error: true
    env:
      BRANCH: assets
    steps:
      
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      
      - name: Download reports
        uses: dawidd6/action-download-artifact@v2
        with:
          name: test-reports
          path: reports
          workflow: tests.yml
  
      - name: Install genbadge
        run: pip install genbadge[tests,coverage]
      
      - name: Generate badges
        run: |
          genbadge tests -o assets/badges/tests-badge.svg
          genbadge coverage -o assets/badges/coverage-badge.svg
          
      - name: Debug directory
        run: ls  

      - name: Commit and push assets
        run: |
          if [[ $(git status --porcelain assets/) ]]; then
            echo "changes detected"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add assets/
            git commit -m "Created assets"
            git push origin ${{ env.BRANCH }}
          else
            echo "no changes"
          fi