name: Test

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        
    steps:
      # setup python
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      # verify python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      # install dependencies
      - name: Install dependencies
        run: python -m pip install .
      - name: Test accex config
        run: python src/accex_config.py
