name: Run tests

on:
  push:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: tests
  cancel-in-progress: true

env:
  ODBC_WIN_ACCESS: https://download.microsoft.com/download/2/4/3/24375141-E08D-4803-AB0E-10F2E3A07AAA/AccessDatabaseEngine_X64.exe
  ODBC_WIN_ACCESS_PATH: C:/PROGRA~1/COMMON~1/MICROS~1/OFFICE14/ACEODBC.DLL
  ODBC_WIN_POSTGRES: https://ftp.postgresql.org/pub/odbc/versions/msi/psqlodbc_16_00_0000-x64.zip
  ODBC_WIN_POSTGRES_PATH: C:/Program Files/psqlODBC/1600/bin/psqlodbc35w.dll

jobs:

  check:
    runs-on: ubuntu-latest
    outputs:
      cached: ${{ steps.src-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Load src cache
        id: src-cache
        uses: actions/cache@v3
        with:
          path: src_cache.txt
          key: ${{ hashFiles( 'src/**/*', 'tests/**/*' ) }}
      
      - name: Create cache file
        run: echo "${{ hashFiles( 'src/**/*', 'tests/**/*' ) }}" > src_cache.txt

      - name: Display cache state
        run: echo "cache hit ${{ steps.src-cache.outputs.cache-hit }}"

  # Run tests
  test:
    needs: check
    # if: ${{ needs.check.outputs.cached != 'true' }}
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: root
    steps:
      
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pip install poetry==1.7.1

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      # setup python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      
      # verify python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # create venv and install dependencies
      - name: Install dependencies
        run: poetry install --with test

      - name: Setup postgres
        run: |
          # start server
          & "$env:PGBIN\pg_ctl.exe" start -D "$env:PGDATA"
          & "$env:PGBIN\pg_ctl.exe" status -D "$env:PGDATA"

      - name: Display ODBC drivers pre install
        run: python scripts/odbc_driver.py ls --info

      # ODBC Driver Postgres
      - name: Get driver hash for postgres
        id: odbc-win-postgres-hash
        run: echo "HASH=$(python -c "import hashlib; print(hashlib.sha256(b'${{ env.ODBC_WIN_POSTGRES }}').hexdigest())")" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Load cached ODBC driver for postgres
        id: cached-odbc-driver-postgres
        uses: actions/cache@v3
        with:
          path: ${{ env.ODBC_WIN_POSTGRES_PATH }}
          key: odbc-${{ runner.os }}-postgres-${{ steps.odbc-win-postgres-hash.outputs.HASH }}

      - name: Download and Install ODBC driver for postgres 
        run: |
          $downloadUrl = "${{ env.ODBC_WIN_POSTGRES }}"
          $downloadPath = "psqlodbc.zip"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
          # extract psqlodbc installer
          $extractPath = "$env:TEMP\psqlodbc"
          Expand-Archive -Path $downloadPath -DestinationPath $extractPath -Force
          # run psqlodbc installer
          $installerPath = "$env:TEMP\psqlodbc\psqlodbc_x64.msi"
          Start-Process -FilePath $installerPath -ArgumentList "/quiet","/passive" -Wait
          # remove downloads
          if (Test-Path $extractPath) { Remove-Item $extractPath -Force -Recurse } else { Write-Host "Item $extractPath does not exist" }
          if (Test-Path $downloadPath) { Remove-Item $downloadPath -Force } else { Write-Host "Item $downloadPath does not exist" }
        if: ${{ steps.cached-odbc-driver-postgres.outputs.cache-hit != 'true' }}
      
      - name: Register ODBC driver for postgres
        run: python scripts/odbc_driver.py register "PostgreSQL Unicode" "${{ env.ODBC_WIN_POSTGRES_PATH }}"
        if: ${{ steps.cached-odbc-driver-postgres.outputs.cache-hit == 'true' }}

      # ODBC Driver Microsoft Access
      - name: Get driver hash for access
        id: odbc-win-access-hash
        run: echo "HASH=$(python -c "import hashlib; print(hashlib.sha256(b'${{ env.ODBC_WIN_ACCESS }}').hexdigest())")" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Load cached ODBC driver for access
        id: cached-odbc-driver-access
        uses: actions/cache@v3
        with:
          path: ${{ env.ODBC_WIN_ACCESS_PATH }}
          key: odbc-${{ runner.os }}-access-${{ steps.odbc-win-access-hash.outputs.HASH }}

      - name: Install Access Database Engine
        run: |
          $downloadUrl = "${{ env.ODBC_WIN_ACCESS }}"
          $installerPath = "$env:TEMP\accessdatabaseengine.exe"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -ArgumentList "/quiet","/passive" -Wait
          Remove-Item $installerPath -Force
        if: ${{ steps.cached-odbc-driver-access.outputs.cache-hit != 'true' }}

      - name: Register ODBC driver for access
        run: python scripts/odbc_driver.py register "Microsoft Access Driver (*.mdb, *.accdb)" "${{ env.ODBC_WIN_ACCESS_PATH }}"
        if: ${{ steps.cached-odbc-driver-access.outputs.cache-hit == 'true' }}

      - name: Display ODBC drivers
        run: python scripts/odbc_driver.py ls --info

      - name: Run tests
        continue-on-error: true
        run: poetry run pytest

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports
  
  assets:
    needs: test
    uses: matthewchen146/access-exodus/.github/workflows/assets.yml@main