name: Test

on: [push]

env:
  POSTGRES_PORT: 5423
  POSTGRES_PASSWORD: root

jobs:
  test:
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        
    steps:
      # setup python
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      
      # verify python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # https://stackoverflow.com/questions/62977821/how-to-cache-poetry-install-for-github-actions
      # cache poetry venv
      - name: Load cached venv
        id: cached-poetry-venv
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install poetry
        run: python -m pip install poetry==1.7.1

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      # create venv and install dependencies
      - name: Install dependencies
        run: poetry install --with test
        if: steps.cached-poetry-venv.outputs.cache-hit != 'true'
      
      # set postgres.conf parameters
      # https://www.postgresql.org/docs/current/config-setting.html

      - name: Setup postgres
        run: |
          # start server
          & "$env:PGBIN\pg_ctl.exe" start -D "$env:PGDATA"
          & "$env:PGBIN\pg_ctl.exe" status -D "$env:PGDATA"

      - name: Install postgres ODBC driver
        run: |
          $downloadUrl = "https://ftp.postgresql.org/pub/odbc/versions/msi/psqlodbc_16_00_0000-x64.zip"
          $downloadPath = "$env:TEMP\psqlodbc.zip"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
          # extract psqlodbc installer
          $extractPath = "$env:TEMP\psqlodbc"
          Expand-Archive -Path $downloadPath -DestinationPath $extractPath -Force
          # run psqlodbc installer
          $installerPath = "$env:TEMP\psqlodbc\psqlodbc_x64.msi"
          Start-Process -FilePath $installerPath -ArgumentList "/quiet","/passive" -Wait
          # remove downloads
          if (Test-Path $extractPath) { Remove-Item $extractPath -Force -Recurse } else { Write-Host "Item $extractPath does not exist" }
          if (Test-Path $downloadPath) { Remove-Item $downloadPath -Force } else { Write-Host "Item $downloadPath does not exist" }

      - name: Install Access Database Engine
        run: |
          $downloadUrl = "https://download.microsoft.com/download/2/4/3/24375141-E08D-4803-AB0E-10F2E3A07AAA/AccessDatabaseEngine_X64.exe"
          $installerPath = "$env:TEMP\accessdatabaseengine.exe"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -ArgumentList "/quiet","/passive" -Wait
          Remove-Item $installerPath -Force

      - name: Display ODBC drivers
        run: Get-OdbcDriver
      
      - name: Display ODBC DSNs
        run: Get-OdbcDsn

      - name: Run tests
        run: poetry run pytest
